name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
               echo "hey there!"
               echo "hello"
      - name: print goodbye
        run: echo "Goodbye"
